import type { DebtScheduleVersion } from "../types.js";

/**
 * Resolve the schedule that existed before the first version generated by a
 * target event. A target can have both an estimated and an official version;
 * both belong to the same event and must be skipped during reversal.
 */
export function getDebtReversalScheduleBaseline({
  debtId,
  targetEventId,
  scheduleVersions,
}: {
  debtId: string;
  targetEventId: string;
  scheduleVersions: DebtScheduleVersion[];
}): DebtScheduleVersion | null {
  const targetVersions = scheduleVersions
    .filter((version) => version.debtId === debtId && version.triggerEventId === targetEventId)
    .sort((a, b) => a.versionNumber - b.versionNumber);

  const firstTargetVersion = targetVersions[0]?.versionNumber;
  if (firstTargetVersion == null) return null;

  return scheduleVersions
    .filter((version) => version.debtId === debtId && version.versionNumber < firstTargetVersion)
    .sort((a, b) => a.versionNumber - b.versionNumber)
    .at(-1) ?? null;
}
