import { describe, expect, it } from "vitest";
import type { DebtScheduleVersion } from "../types.js";
import { getDebtReversalScheduleBaseline } from "./debtReversalSchedule.js";

function schedule(overrides: Partial<DebtScheduleVersion> = {}): DebtScheduleVersion {
  return {
    id: "v1",
    debtId: "debt-1",
    versionNumber: 1,
    effectiveDate: "2026-01-01",
    reason: "initial",
    scheduleSource: "contractual",
    isAuthoritative: true,
    triggerEventId: null,
    notes: "",
    createdByUserId: "user-1",
    createdAt: "2026-01-01T00:00:00Z",
    ...overrides,
  };
}

describe("getDebtReversalScheduleBaseline", () => {
  it("returns the schedule before a single target version", () => {
    const baseline = schedule();
    const target = schedule({ id: "v2", versionNumber: 2, triggerEventId: "event-p" });
    expect(getDebtReversalScheduleBaseline({ debtId: "debt-1", targetEventId: "event-p", scheduleVersions: [baseline, target] })).toBe(baseline);
  });

  it("skips every schedule version generated by the same target event", () => {
    const baseline = schedule();
    const estimated = schedule({ id: "v2", versionNumber: 2, triggerEventId: "event-p", scheduleSource: "estimated", isAuthoritative: false });
    const official = schedule({ id: "v3", versionNumber: 3, triggerEventId: "event-p" });
    expect(getDebtReversalScheduleBaseline({ debtId: "debt-1", targetEventId: "event-p", scheduleVersions: [baseline, estimated, official] })).toBe(baseline);
  });

  it("uses the latest unrelated version before the first target version", () => {
    const original = schedule();
    const unrelated = schedule({ id: "v2", versionNumber: 2, triggerEventId: "event-other", reason: "manual_adjustment" });
    const target = schedule({ id: "v3", versionNumber: 3, triggerEventId: "event-p" });
    const targetReplay = schedule({ id: "v4", versionNumber: 4, triggerEventId: "event-p" });
    expect(getDebtReversalScheduleBaseline({ debtId: "debt-1", targetEventId: "event-p", scheduleVersions: [original, unrelated, target, targetReplay] })).toBe(unrelated);
  });

  it("returns null when the target generated no schedule", () => {
    expect(getDebtReversalScheduleBaseline({ debtId: "debt-1", targetEventId: "event-p", scheduleVersions: [schedule()] })).toBeNull();
  });
});
